### ISSUE TITLE
Inc typo

### ISSUE THREAD

**Issue by CalebLarsen** [AZHenley/superoptimizer#1]
https://github.com/AZHenley/superoptimizer/blob/b927c3b2eb8280e83859541a4d63ce874ac3d75d/cpu.py#L29

The increment instruction is implemented as
`state[mem] += state[mem] + 1`

If I understand correctly, this is probably just wires getting crossed of both `state[mem] = state[mem] + 1` and `state[mem] += 1`

**Comment by AZHenley** [comment]
Thanks for catching this!

**Comment by CalebLarsen** [comment]
Very cool project! Thanks for this and the blog post
